services:
  web:
    build: .
    container_name: pengaduan_apache
    ports:
      - "8005:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: pengaduan_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pengaduan_kampus
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

